### ISSUE TITLE
problems installing on a Homebrew setup

### ISSUE THREAD

**Issue by syntacticsugar** [moonmaster9000/bird#1]
Hi...

I am trying to install this on my work computer, a Mac OS X with Homebrew.  I ran 'cabal update && cabal install bird' and ran into the following error:

`Downloading the latest package list from hackage.haskell.org
Resolving dependencies...
Downloading base-unicode-symbols-0.2.2.3...
Configuring base-unicode-symbols-0.2.2.3...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading base64-bytestring-0.1.1.1...
Configuring base64-bytestring-0.1.1.1...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading blaze-builder-0.3.1.0...
Configuring blaze-builder-0.3.1.0...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading dlist-0.5...
Configuring dlist-0.5...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading hslogger-1.1.5...
Configuring hslogger-1.1.5...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading rallod-0.0.1...
Configuring rallod-0.0.1...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading sendfile-0.7.6...
Configuring sendfile-0.7.6...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading transformers-base-0.4.1...
Configuring transformers-base-0.4.1...
ghc: could not execute: /Developer/usr/bin/gcc
Downloading utf8-string-0.3.7...
Configuring utf8-string-0.3.7...
ghc: could not execute: /Developer/usr/bin/gcc
cabal: Error: some packages failed to install:
MissingH-1.1.1.0 depends on hslogger-1.1.5 which failed to install.
base-unicode-symbols-0.2.2.3 failed during the configure step. The exception
was:
ExitFailure 1
base64-bytestring-0.1.1.1 failed during the configure step. The exception was:
ExitFailure 1
bird-0.0.19 depends on utf8-string-0.3.7 which failed to install.
blaze-builder-0.3.1.0 failed during the configure step. The exception was:
ExitFailure 1
blaze-html-0.4.3.3 depends on blaze-builder-0.3.1.0 which failed to install.
data-default-0.4.0 depends on dlist-0.5 which failed to install.
dlist-0.5 failed during the configure step. The exception was:
ExitFailure 1
hack-2012.2.6 depends on dlist-0.5 which failed to install.
hack-handler-happstack-2009.12.20 depends on utf8-string-0.3.7 which failed to
install.
happstack-server-7.0.0 depends on utf8-string-0.3.7 which failed to install.
hslogger-1.1.5 failed during the configure step. The exception was:
ExitFailure 1
monad-control-0.3.1.1 depends on transformers-base-0.4.1 which failed to
install.
rallod-0.0.1 failed during the configure step. The exception was:
ExitFailure 1
sendfile-0.7.6 failed during the configure step. The exception was:
ExitFailure 1
transformers-base-0.4.1 failed during the configure step. The exception was:
ExitFailure 1
utf8-string-0.3.7 failed during the configure step. The exception was:
ExitFailure 1`

I also had issues trying to install Haskell on my Mac os x :(  Do you happen to use Homebrew by any chance?

**Comment by moonmaster9000** [comment]
hi, sorry, it appears that it can't find your gcc (it's usually in /usr/bin/gcc, not /Developer/usr/bin/gcc).
